GET http://localhost:8000/login?username=MelMel&password=melodyHam
Accept: application/json

###

GET http://localhost:8000/login?username=ManMan&password=ManiHamed
Accept: application/json

###

GET http://localhost:8000/login?username=PoopPoop&password=PoopShir
Accept: application/json

###

POST http://localhost:8000/signup
Content-Type: application/json

{
  "username": "MelMel",
  "firstName": "Melody",
  "lastName": "Ham",
  "password": "melodyHam",
  "email": "manely.g.hamedani@gmail.com",
  "phoneNumber": "09123111510",
  "country": "Iran",
  "birthDate": "2004-01-21"
}

###

POST http://localhost:8000/signup
Content-Type: application/json

{
  "username": "ManMan",
  "firstName": "Mani",
  "lastName": "Ham",
  "password": "ManiHamed",
  "email": "mani.hamedani@gmail.com",
  "phoneNumber": "09121074092",
  "country": "Iran",
  "birthDate": "1973-09-01"
}

###

POST http://localhost:8000/signup
Content-Type: application/json

{
  "username": "PoopPoop",
  "firstName": "Poop",
  "lastName": "Shir",
  "password": "PoopShir",
  "email": "poop.shir@gmail.com",
  "phoneNumber": "09126238112",
  "country": "Iran",
  "birthDate": "1977-09-01"
}

###

POST http://localhost:8000/set-user-image
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

< ./avatar.json

###

POST http://localhost:8000/set-user-image
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

< ./header3.json

###

POST http://localhost:8000/set-user-info
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

{
  "bio": "Hey! It is my test bio.",
  "location": "SomeWhere",
  "website": "https://apple.com"
}

###

POST http://localhost:8000/follow?username=ManMan
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

POST http://localhost:8000/follow?username=PoopPoop
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

GET http://localhost:8000/list-followers?username=ManMan
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

GET http://localhost:8000/list-following?username=MelMel
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

GET http://localhost:8000/search?quest=hAm
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

POST http://localhost:8000/tweet
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNYW5NYW4iLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjcxOTEwNiwiZXhwIjoxNjg4NzgwNzE5MTA2fQ.RmIHhjaDZG8NRHCgllnJLMKutJtyvf3FpIoDj6XNi30

< ./tweet.json

###

POST http://localhost:8000/retweet
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJQb29wUG9vcCIsImlkIjowLCJhdWQiOiJ1c2VyIiwiaWF0IjoxNjg3OTE2NzUwNjAxLCJleHAiOjE2ODg3ODA3NTA2MDF9.hW5g8bbThwjWqUjEf7om2-ZbW0c1pFo4Aomv7DaDZcc

< ./retweet.json

###

POST http://localhost:8000/quote
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

< ./quote.json

###

POST http://localhost:8000/like?id=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJQb29wUG9vcCIsImlkIjowLCJhdWQiOiJ1c2VyIiwiaWF0IjoxNjg3OTE2NzUwNjAxLCJleHAiOjE2ODg3ODA3NTA2MDF9.hW5g8bbThwjWqUjEf7om2-ZbW0c1pFo4Aomv7DaDZcc

###

POST http://localhost:8000/like?id=2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNYW5NYW4iLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjcxOTEwNiwiZXhwIjoxNjg4NzgwNzE5MTA2fQ.RmIHhjaDZG8NRHCgllnJLMKutJtyvf3FpIoDj6XNi30

###

POST http://localhost:8000/unlike?id=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJQb29wUG9vcCIsImlkIjowLCJhdWQiOiJ1c2VyIiwiaWF0IjoxNjg3OTE2NzUwNjAxLCJleHAiOjE2ODg3ODA3NTA2MDF9.hW5g8bbThwjWqUjEf7om2-ZbW0c1pFo4Aomv7DaDZcc

###

POST http://localhost:8000/reply
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

< ./reply.json

###

POST http://localhost:8000/block?username=PoopPoop
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

POST http://localhost:8000/timeline?date=1687917241184
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

POST http://localhost:8000/unblock?username=PoopPoop
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###

POST http://localhost:8000/filter?quest=t
Authorization: eyJhbGciOiJIUzI1NiIsInR5cGUiOiJKV1QifQ.eyJzdWIiOiJNZWxNZWwiLCJpZCI6MCwiYXVkIjoidXNlciIsImlhdCI6MTY4NzkxNjU4NDQ1NSwiZXhwIjoxNjg4NzgwNTg0NDU1fQ.Am3pAv9hAwlqMbXmS3uTDEplxLwLrcXagThBzCuDt3c

###
